name: Run E2E Tests

on: [pull_request]

jobs:
  run-e2e-tests:
    name: Run E2E Tests
    runs-on: ubuntu-latest

    services:
      postgres:
        image: bitnamilegacy/postgresql
        ports:
          - 5432:5432
        environment:
          - POSTGRESQL_USERNAME=docker
          - POSTGRESQL_PASSWORD=docker
          - POSTGRESQL_DATABASE=apisolid

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.14.0
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Run e2e tests
        run: npm run test:e2e
        env:
          NODE_ENV: dev
          JWT_SECRET: testing
          PORT: 3333
          DATABASE_URL: "postgresql://docker:docker@localhost:5432/apisolid?schema=public"
